"use client";
import { useEffect, useState } from "react";

function applicationKey(value: string) { const padding = "=".repeat((4 - value.length % 4) % 4); const raw = atob((value + padding).replace(/-/g, "+").replace(/_/g, "/")); return Uint8Array.from([...raw].map((char) => char.charCodeAt(0))); }

export function PushNotificationOptIn({ hasFollowedTeams, publicKey }: { hasFollowedTeams: boolean; publicKey: string }) {
  const [enabled, setEnabled] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const supported = typeof window !== "undefined" && "serviceWorker" in navigator && "PushManager" in window && "Notification" in window;
  useEffect(() => { if (!supported) return; navigator.serviceWorker.ready.then((registration) => registration.pushManager.getSubscription()).then((subscription) => setEnabled(Boolean(subscription))); }, [supported]);
  async function toggle() { setBusy(true); setMessage(null); try { const registration = await navigator.serviceWorker.ready; const current = await registration.pushManager.getSubscription(); if (current) { await fetch(`/api/account/push-subscription?endpoint=${encodeURIComponent(current.endpoint)}`, { method: "DELETE" }); await current.unsubscribe(); setEnabled(false); setMessage("Match alerts are off on this device."); } else { const permission = await Notification.requestPermission(); if (permission !== "granted") throw new Error("Notifications were not allowed in this browser."); const subscription = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: applicationKey(publicKey) }); const response = await fetch("/api/account/push-subscription", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(subscription.toJSON()) }); if (!response.ok) { await subscription.unsubscribe(); const body = await response.json().catch(() => ({})); throw new Error(body.error ?? "Could not enable alerts."); } setEnabled(true); setMessage("You’ll hear from your padi near kickoff and at full time."); } } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update notifications."); } finally { setBusy(false); } }
  return <section className="panel push-opt-in"><div><span className="section-kicker">Team alerts</span><h2>Matchday notifications</h2><p className="muted">Kickoff-soon and full-time updates for teams you follow. Analysis only — never promises.</p></div>{!hasFollowedTeams ? <p className="notice">Follow at least one team above to unlock alerts.</p> : !publicKey ? <p className="notice">Push is not configured in this environment yet.</p> : !supported ? <p className="notice">This browser does not support web push.</p> : <button className={`button ${enabled ? "secondary" : "primary"}`} type="button" disabled={busy} onClick={toggle}>{busy ? "Updating…" : enabled ? "Turn off alerts" : "Enable team alerts"}</button>}{message ? <p className="small" role="status">{message}</p> : null}</section>;
}
