import { writeFileSync } from "node:fs";
import {
  DATA_AVAILABILITY_STATES,
  DECISION_STATUSES,
  FIXTURE_STATUSES,
  PUBLICATION_STATUSES,
  SETTLEMENT_STATUSES
} from "../src/lib/domain/states";
import { coherentCells, explainIncoherence, REPRESENTATIVE_CELLS } from "../src/lib/domain/stateMatrix";

/**
 * docs/state-test-matrix.md is generated, never hand-edited.
 *
 * A hand-written matrix drifts from the code the first time a state is added,
 * and then documents a product that no longer exists. Regenerate with
 * `npm run docs:state-matrix`; the release gate fails if the checked-in file
 * differs from what the model produces.
 */
const cells = coherentCells();
const fixtures = FIXTURE_STATUSES.filter((s) => s !== "unknown");
const crossProduct =
  fixtures.length *
  DATA_AVAILABILITY_STATES.length *
  DECISION_STATUSES.length *
  (PUBLICATION_STATUSES.length + 1) *
  SETTLEMENT_STATUSES.length;

/** Count coherent cells per value so the doc shows where the model is tight. */
function tally(pick: (cell: (typeof cells)[number]) => string, values: readonly string[]): string[] {
  return values.map((value) => {
    const n = cells.filter((cell) => pick(cell) === value).length;
    return `| \`${value}\` | ${n} |`;
  });
}

const sampleIncoherent = [
  { fixture: "scheduled", data: "complete", decision: "pick", publication: "published", settlement: "won" },
  { fixture: "finished", data: "complete", decision: "pick", publication: null, settlement: "won" },
  { fixture: "scheduled", data: "unavailable", decision: "pass", publication: null, settlement: "unsettled" },
  { fixture: "scheduled", data: "complete", decision: "lean", publication: "published", settlement: "unsettled" },
  { fixture: "abandoned", data: "complete", decision: "pick", publication: "published", settlement: "won" },
  { fixture: "scheduled", data: "stale", decision: "pick", publication: null, settlement: "unsettled" }
] as const;

const lines: string[] = [];
lines.push("# State test matrix");
lines.push("");
lines.push("<!-- GENERATED by scripts/generate-state-matrix-doc.ts. Do not edit by hand. -->");
lines.push("");
lines.push("Five independent state dimensions describe any fixture the product can show.");
lines.push("They are defined once in [`src/lib/domain/states.ts`](../src/lib/domain/states.ts)");
lines.push("and constrained against each other in [`src/lib/domain/stateMatrix.ts`](../src/lib/domain/stateMatrix.ts).");
lines.push("");
lines.push("## Dimensions");
lines.push("");
lines.push("| Dimension | Values |");
lines.push("|---|---|");
lines.push(`| Fixture lifecycle | ${fixtures.map((v) => `\`${v}\``).join(", ")} |`);
lines.push(`| Data state | ${DATA_AVAILABILITY_STATES.map((v) => `\`${v}\``).join(", ")} |`);
lines.push(`| Decision state | ${DECISION_STATUSES.map((v) => `\`${v}\``).join(", ")} |`);
lines.push(`| Publication state | ${["none", ...PUBLICATION_STATUSES].map((v) => `\`${v}\``).join(", ")} |`);
lines.push(`| Settlement state | ${SETTLEMENT_STATUSES.map((v) => `\`${v}\``).join(", ")} |`);
lines.push("");
lines.push("## Coherence");
lines.push("");
lines.push(`The unconstrained cross-product is **${crossProduct.toLocaleString()}** combinations.`);
lines.push(`Most describe situations that cannot exist. Applying the coherence rules leaves`);
lines.push(`**${cells.length.toLocaleString()}** cells — ${((cells.length / crossProduct) * 100).toFixed(1)}% of the space.`);
lines.push("");
lines.push("The reduction is the point: every excluded cell is a contradiction the product");
lines.push("is now forbidden to render, and the exclusions are executable rules rather than");
lines.push("prose. A cell that cannot exist cannot be tested for, and must instead be");
lines.push("prevented.");
lines.push("");
lines.push("### Coherent cells by fixture status");
lines.push("");
lines.push("| Fixture status | Coherent cells |");
lines.push("|---|---|");
lines.push(...tally((c) => c.fixture, fixtures));
lines.push("");
lines.push("### Coherent cells by data state");
lines.push("");
lines.push("| Data state | Coherent cells |");
lines.push("|---|---|");
lines.push(...tally((c) => c.data, DATA_AVAILABILITY_STATES));
lines.push("");
lines.push("`unavailable` is the narrowest by design: a failed read constrains the decision to");
lines.push("`unavailable` and forbids publication outright.");
lines.push("");
lines.push("## Worked exclusions");
lines.push("");
lines.push("Each of these is individually representable and jointly nonsense.");
lines.push("");
lines.push("| Combination | Rejected because |");
lines.push("|---|---|");
for (const cell of sampleIncoherent) {
  const why = explainIncoherence(cell as never);
  const label = `${cell.fixture} / ${cell.data} / ${cell.decision} / ${cell.publication ?? "none"} / ${cell.settlement}`;
  lines.push(`| \`${label}\` | ${why.join("; ")} |`);
}
lines.push("");
lines.push("## Representative cells");
lines.push("");
lines.push("The cross-surface suite renders all ten public surfaces for each of these.");
lines.push("Every dimension value appears at least once — enforced by a test, so the set");
lines.push("cannot quietly stop exercising a state.");
lines.push("");
lines.push("| ID | Fixture | Data | Decision | Publication | Settlement | Why this cell |");
lines.push("|---|---|---|---|---|---|---|");
for (const { id, cell, note } of REPRESENTATIVE_CELLS) {
  lines.push(
    `| \`${id}\` | ${cell.fixture} | ${cell.data} | ${cell.decision} | ${cell.publication ?? "—"} | ${cell.settlement} | ${note} |`
  );
}
lines.push("");
lines.push("## How this is enforced");
lines.push("");
lines.push("| Check | File |");
lines.push("|---|---|");
lines.push("| The model agrees with itself | `src/test/state-matrix.test.ts` |");
lines.push("| Surfaces agree with each other | `src/test/cross-surface-consistency.test.tsx` |");
lines.push("| Forbidden states never render | `src/test/prohibited-contradictions.test.tsx` |");
lines.push("| Production rows stay coherent | `scripts/reconcile-truth.mjs` |");
lines.push("");

writeFileSync("docs/state-test-matrix.md", lines.join("\n"), "utf8");
console.log(`docs/state-test-matrix.md written — ${cells.length} coherent cells of ${crossProduct}`);
