-- Superseded intermediate. Intentionally empty.
--
-- First apply of `op_latest_odds_for_fixtures`, the
-- newest-quote-per-selection read.
--
-- Recorded in `supabase_migrations.schema_migrations` as `20260728125724
-- latest_odds_for_fixtures`, applied through the Supabase MCP tool, which
-- assigns its own version at apply time rather than using a committed
-- filename. The change was folded into
-- `20260728131500_latest_odds_for_fixtures.sql`, which is what a fresh
-- environment runs.
--
-- Verified against production 2026-08-07: `op_latest_odds_for_fixtures`
-- exists in production and reads `op_current_odds`, which is the
-- 20260803170000 definition — several revisions past this one.
--
-- This file carries no statements on purpose. Its only job is to hold the
-- version, so the local migrations directory and the remote ledger list
-- the same set. Without it `supabase db push` reports "Remote migration
-- versions not found in local migrations directory" and the Supabase
-- Preview check fails. The ledger row is the record of what actually ran
-- and is kept as is; replaying its statements here would re-run history
-- out of order. See docs/migration-ledger.md.
